List and Delete station are done

diff --git a/search b/search
--- a/search
+++ b/search
@@ -42,9 +42,131 @@ _save_play() {
     echo "Save & Play"
 }
 
+search_by() {
+    KEY=$1
+    SEARCH_RESULTS=$(mktemp /tmp/radio_searches.json)
+    echo
+    read -rp "Type a $KEY to search: " RES
+    OPTS=()
+    for TAG in "${RES[@]}"; do
+        OPTS+=(-d "$KEY=$TAG")
+    done
+
+    curl -X POST "${OPTS[@]}" "$SEARCH_URL" -o "$SEARCH_RESULTS" >&/dev/null
+
+    jq -r '.[].name' <"$SEARCH_RESULTS" | nl
+    echo
+    read -rp "Select a number. " ANS
+    # echo "$ANS"
+
+    # URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"$SEARCH_RESULTS")
+    search_submenu "$ANS"
+    # rm "$SEARCH_RESULTS"
+}
+
+# uses radio-browser.info bytag and grep
+# use country codes
+# after search result ask a number to play/save
+# tera search jazz US
+fn_search() {
+    # curl -X POST -d 'tag=jazz&countrycode=au&state=queensland' http://91.132.145.114/json/stations/search
+    # curl -X POST -d 'tag=$1' -d 'countrycode=AU' $SEARCH_URL
+    OPTS=()
+    if [ $# -ge 1 ] && [ -n "$1" ]; then
+        OPTS+=(-d "tag=$1")
+    fi
+    # echo "countrycode: $COUNTRYCODE"
+    if [ -n "$COUNTRYCODE" ]; then
+        OPTS+=(-d "countrycode=$COUNTRYCODE")
+    fi
+    # echo "name: $NAME"
+    if [ -n "$NAME" ]; then
+        OPTS+=(-d "name=$NAME")
+    fi
+    # echo "language: $LANGUAGE"
+    if [ -n "$LANGUAGE" ]; then
+        OPTS+=(-d "language=$LANGUAGE")
+    fi
+    # echo "state: $STATE"
+    if [ -n "$STATE" ]; then
+        OPTS+=(-d "state=$STATE")
+    fi
+    # echo "OPTS are : "
+    # echo "${OPTS[@]}"
+    SEARCH_RESULTS=$(mktemp /tmp/radio_searches.json)
+    SEARCH_RESULT=$(mktemp /tmp/radio_search.json)
+    TEMP_FILE=$(mktemp /tmp/radio_favorite.json)
+    TEMP_FILE2=$(mktemp /tmp/radio_favorite2.json)
+    echo
+    curl -X POST "${OPTS[@]}" "$SEARCH_URL" -o "$SEARCH_RESULTS" >&/dev/null
+    jq -r '.[].name' <"$SEARCH_RESULTS" | nl
+    echo
+    # cat "$SEARCH_RESULTS"
+    read -rp "Select a number. " NUM
+    # STATION_NUM=$NUM
+    jq ".[$NUM]" <"$SEARCH_RESULTS" >"$SEARCH_RESULT"
+    # echo "Station no.: $STATION_NUM"
+    echo
+    echo "Do you want to: "
+    echo
+    PS3="Enter a number: "
+    select LIST in "Play" "Save" "Save & play" "Create"; do
+        # echo "Selected list: $LIST"
+        break
+    done
+    echo "you selected $LIST"
+    echo "reply $REPLY"
+    # rm "$SEARCH_RESULTS"
+    # rm "/tmp/*.json"
+    # exit
+
+    case $REPLY in
+    1)
+        url=$(jq -r '.url_resolved' <"$1")
+        _play "$url"
+        ;;
+    2)
+        fn_save "$@"
+        ;;
+    3)
+        fn_save_play
+        ;;
+    4)
+        fn_create
+        echo "hi"
+        ;;
+    --) ;; # no subcommand, arguments only
+    esac
+
+    echo "Searching ..."
+    # works
+
+    curl $RADIO_BROWSER/"$1" | jq --arg COUNTRYCODE "$COUNTRYCODE" '[.[] | select(.countrycode==$COUNTRYCODE)]' >"$TEMP_FILE"
+    # shows station names
+    jq -r '.[].name' <"$TEMP_FILE" | nl
+
+    # ls "$TEMP_FILE"
+    # cat "$TEMP_FILE"
+    # after search result ask a number to play/save
+    read -rp "Select a number to add to your favirite list. " ANS
+    # get the content
+    jq ".[$ANS-1]" <"$TEMP_FILE" >"$TEMP_FILE2"
+
+    # 1
+    # jq '. += ["$TEMP_FILE2"]' "$FAVORITE_FULL" "$TEMP_FILE2"
+    # 2
+    # jq --argjson TEMP "$(cat "$TEMP_FILE2")" '. += [$TEMP]' "$FAVORITE_FULL" >"$TEMP_FILE" && mv "$TEMP_FILE" "$FAVORITE_FULL"
+    jq '. += [input]' "$FAVORITE_FULL" "$TEMP_FILE2" >"$TEMP_FILE" && mv "$TEMP_FILE" "$FAVORITE_FULL"
+
+    # cleanup
+    rm -f "$TEMP_FILE"
+    rm -f "$TEMP_FILE2"
+    echo "Added a new station."
+}
+
 search_submenu() {
     echo -ne "
-$SCRIPT_NAME SELECT:
+$APP_NAME SELECT to:
 $(ColorGreen '1)') Play
 $(ColorGreen '2)') Save
 $(ColorGreen '3)') Go back to the Main menu
@@ -56,12 +178,12 @@ $(ColorBlue 'Choose an option:') "
     1)
         echo "Playing $ANS"
         _search_play "$ANS"
-        menu
+        search_menu
         ;;
     2)
         echo "Saving $ANS"
         _save_station "$ANS"
-        menu
+        search_menu
         ;;
     3)
         echo "Go back to the Main menu"
@@ -80,22 +202,58 @@ $(ColorBlue 'Choose an option:') "
     esac
 }
 
-search_by() {
-    KEY=$1
-    SEARCH_RESULTS=$(mktemp /tmp/radio_searches.json)
-    read -rp "Type a $KEY to search. " RES
-    OPTS=()
-    for TAG in "${RES[@]}"; do
-        OPTS+=(-d "$KEY=$TAG")
-    done
-
-    curl -X POST "${OPTS[@]}" "$SEARCH_URL" -o "$SEARCH_RESULTS" >&/dev/null
-
-    jq -r '.[].name' <"$SEARCH_RESULTS" | nl
-    read -rp "Select a number. " ANS
-    # echo "$ANS"
-
-    # URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"$SEARCH_RESULTS")
-    search_submenu "$ANS"
-    # rm "$SEARCH_RESULTS"
+search_menu() {
+    # cleanup /tmp/radio_searches.json
+    _clean_tmp
+    echo -ne "
+$APP_NAME SEARCH MENU:
+$(ColorGreen '1)') Tag
+$(ColorGreen '2)') Name
+$(ColorGreen '3)') Language 
+$(ColorGreen '4)') Country code
+$(ColorGreen '5)') State
+$(ColorGreen '6)') Advanced search
+$(ColorGreen '7)') Main Menu
+$(ColorGreen '0)') Exit
+$(ColorBlue 'Choose an option:') "
+    read -r a
+    case $a in
+    1)
+        search_by tag
+        menu
+        ;;
+    2)
+        search_by name
+        menu
+        ;;
+    3)
+        echo "Search by language"
+        search_by language
+        menu
+        ;;
+    4)
+        search_by countrycode
+        menu
+        ;;
+    5)
+        search_by state
+        menu
+        ;;
+    6)
+        advanced_search
+        menu
+        ;;
+    7)
+        menu
+        ;;
+    0)
+        echo "Bye bye."
+        exit 0
+        ;;
+    *)
+        echo -e $red"Wrong option."$clear
+        # WrongCommand
+        exit 1
+        ;;
+    esac
 }
