_graceful_exit added

diff --git a/search b/search
--- a/search
+++ b/search
@@ -35,7 +35,10 @@ _search_play() {
     jq -r ".[$ANS-1]" <"$SEARCH_RESULTS" >"$TEMP_FILE"
     URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"$SEARCH_RESULTS")
     if [[ -n $URL_RESOLVED ]]; then
-        mpv "$URL_RESOLVED"
+        mpv "$URL_RESOLVED" || {
+            echo "Search: Can't play mpv."
+            exit 1
+        }
     else
         echo "url_resolved can't be found. Exiting ..."
         exit 1
