Basic search works

diff --git a/tera b/tera
--- a/tera
+++ b/tera
@@ -3,14 +3,13 @@
 set -eu
 
 # shellcheck disable=SC2034
-VERSION="0.0.1"
-FAVORITE_PATH="$HOME/.tera"
+VERSION="0.0.2"
+FAVORITE_PATH="$HOME/.cora"
 FAVORITE_FILE="favorite.json"
 FAVORITE_FULL="${FAVORITE_PATH}/${FAVORITE_FILE}"
 SCRIPT_NAME=$(basename "$0")
-TEMP_FILE=$(mktemp)
-TEMP_FILE2=$(mktemp)
 RADIO_BROWSER="https://de1.api.radio-browser.info/json/stations/bytag/"
+SEARCH_URL="http://91.132.145.114/json/stations/search"
 
 myrealpath() {
     local LINK REALPATH
@@ -41,6 +40,8 @@ fi
 script_dir="${script_path%/*}"
 # shellcheck disable=SC1091
 source "${script_dir}/getoptions"
+# shellcheck disable=SC1091
+# source "${script_dir}/lib"
 
 check_cmd() {
     if [[ ! $(command -v "$1") ]]; then
@@ -54,22 +55,65 @@ check_cmd() {
 check_cmd mpv
 check_cmd jq
 
+# cleanup() {
+#     if [ -f "$TEMP_FILE" ] && [[ "$TEMP_FILE" =~ ".json"$ ]]; then
+#         rm -f "$TEMP_FILE"
+#     fi
+#     if [ -f "$TEMP_FILE2" ] && [[ "$TEMP_FILE2" =~ ".json"$ ]]; then
+#         rm -f "$TEMP_FILE2"
+#     fi
+# }
+
+# trap cleanup EXIT
+# trap cleanup ERR
+
 # check ~/.tera/favorite
-if [ ! -d "${FAVORITE_PATH}" ]; then
+if [ ! -d "$FAVORITE_PATH" ]; then
     mkdir "$FAVORITE_PATH"
 fi
-if [ ! -f "${FAVORITE_FULL}" ]; then
-    touch "${FAVORITE_FULL}"
+if [ ! -f "$FAVORITE_FULL" ]; then
+    touch "$FAVORITE_FULL"
 fi
 
+_fav_list() {
+    arr=("$FAVORITE_PATH"/*.json)
+    # for ((i = 0; i < ${#arr[@]}; i++)); do
+    #     #do something to each element of array
+    #     echo "${arr[$i]}"
+    # done
+    list=()
+    for f in "${arr[@]}"; do
+        name=$(basename "$f")
+        list+=("${name%.*}")
+    done
+    echo "${list[@]}"
+}
+
 _station_list() {
-    jq -r '.[] | .name' <"${FAVORITE_FULL}"
+    jq -r '.[] | .name' <"$1"
 }
 # # opens a favorite list and select number to play a station
 # tera play
 fn_play() {
+    # check if a list is empty
+    lists=$(_fav_list)
+    lists=""
+    echo "$lists"
+    if [ -z "$lists" ]; then
+        echo "lists is empty"
+        echo "try $SCRIPT_NAME search"
+    fi
+
+    PS3="Enter a number: "
+    select LIST in $(_fav_list); do
+        # echo "Selected list: $LIST"
+        break
+    done
+
+    # read -rp "Type a list number.   " LIST
+
     echo "Select a number to play."
-    STATIONS=$(_station_list)
+    STATIONS=$(_station_list "$LIST")
     echo "$STATIONS" | nl
     echo
     read -rp "Type number to play.   " ANS
@@ -77,6 +121,7 @@ fn_play() {
     URL_RESOLVED=$(jq -r ".[$ANS-1] |.url_resolved" <"${FAVORITE_FULL}")
     echo "$URL_RESOLVED"
     mpv "$URL_RESOLVED"
+    echo "wow"
 }
 
 # uses radio-browser.info bytag and grep
@@ -84,20 +129,84 @@ fn_play() {
 # after search result ask a number to play/save
 # tera search jazz US
 fn_search() {
+    # curl -X POST -d 'tag=jazz&countrycode=au&state=queensland' http://91.132.145.114/json/stations/search
+    # curl -X POST -d 'tag=$1' -d 'countrycode=AU' $SEARCH_URL
+    # check $1
+    # if [ -z $1 ];
+
+    # fi
+    # echo "1: $1"
+    # if [ $# -ge 1 ] && [ -n "$1" ]; then
+    #     TA="-d 'tag=$1'"
+    # else
+    #     TA=""
+    # fi
+    # echo "countrycode: $COUNTRYCODE"
+    # if [ -n "$COUNTRYCODE" ]; then
+    #     CC="-d 'countrycode=$COUNTRYCODE'"
+    # else
+    #     CC=""
+    # fi
+    # echo "name: $NAME"
+    # if [ -n "$NAME" ]; then
+    #     NA="-d 'name=$NAME'"
+    # else
+    #     NA=""
+    # fi
+    # echo "language: $LANGUAGE"
+    # if [ -n "$LANGUAGE" ]; then
+    #     LA="-d 'language=$LANGUAGE'"
+    # else
+    #     LA=""
+    # fi
+    # echo "state: $STATE"
+    # if [ -n "$STATE" ]; then
+    #     ST="-d 'state=$STATE'"
+    # else
+    #     ST=""
+    # fi
+
+    # curl_opts=$(echo "$TA $CC $NA $LA $ST" | tr -s ' ')
+    # curl_opts=("$TA $CC $NA $LA $ST")
+    # OPTS=$(echo "${curl_opts[@]}" | tr -s ' ')
+    # curl_opts=(-d'tag=jazz' -d'state=queensland')
+    # echo "$curl_opts"
+    # OPTS=$(echo "$TA $CC $NA $LA $ST" | tr -s ' ')
+    # echo "$OPTS"
+    OPTS="-d 'tag=jazz' -d 'language=english' -d 'state=queensland'"
+    # curl -X POST -d 'tag=jazz' -d 'language=english' -d 'state=queensland' "$SEARCH_URL"
+    # curl -X POST "$OPTS" "$SEARCH_URL"
+    # exit
+    TEMP_FILE=$(mktemp /tmp/cora_favorite.json)
+    TEMP_FILE2=$(mktemp /tmp/cora_favorite2.json)
     echo "Searching ..."
+    # works
     COUNTRYCODE=$2
-    curl $RADIO_BROWSER/"$1" | jq --arg COUNTRYCODE "$COUNTRYCODE" '.[] | select(.countrycode==$COUNTRYCODE) | .name' | tee "$TEMP_FILE" | nl
-    ls "$TEMP_FILE"
+    curl $RADIO_BROWSER/"$1" | jq --arg COUNTRYCODE "$COUNTRYCODE" '[.[] | select(.countrycode==$COUNTRYCODE)]' >"$TEMP_FILE"
+    # shows station names
+    jq -r '.[].name' <"$TEMP_FILE" | nl
+
+    # ls "$TEMP_FILE"
+    # cat "$TEMP_FILE"
     # after search result ask a number to play/save
     read -rp "Select a number to add to your favirite list.   " ANS
     # get the content
-    # jq ".[$ANS-1]" "$TEMP_FILE"
-    rm "$TEMP_FILE"
-    # jq '.[] += "$ANS"'
+    jq ".[$ANS-1]" <"$TEMP_FILE" >"$TEMP_FILE2"
 
+    # 1
+    # jq '. += ["$TEMP_FILE2"]' "$FAVORITE_FULL" "$TEMP_FILE2"
+    # 2
+    # jq --argjson TEMP "$(cat "$TEMP_FILE2")" '. += [$TEMP]' "$FAVORITE_FULL" >"$TEMP_FILE" && mv "$TEMP_FILE" "$FAVORITE_FULL"
+    jq '. += [input]' "$FAVORITE_FULL" "$TEMP_FILE2" >"$TEMP_FILE" && mv "$TEMP_FILE" "$FAVORITE_FULL"
+
+    # cleanup
+    rm -f "$TEMP_FILE"
+    rm -f "$TEMP_FILE2"
+    echo "Added a new station."
 }
 
 fn_delete() {
+    TEMP_FILE=$(mktemp)
     echo "Select a number to delete."
     STATIONS=$(_station_list)
     echo "$STATIONS" | nl
@@ -137,6 +246,10 @@ parser_definition_search() {
     setup REST help:usage abbr:true -- \
         "Usage: ${2##*/} search "
     msg -- 'Search a station.'
+    param COUNTRYCODE -c --countrycode -- "accepts --countrycode value / --countrycode=value"
+    param NAME -n --name -- "accepts --name value / --name=value"
+    param LANGUAGE -l --lang -- "accepts --lang value / --lang=value"
+    param STATE -s --state -- "accepts --state value / --state=value"
     disp :usage -h --help
 }
 
